# Docker Compose para NaSalinha Frontend
services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: nasalinha-frontend
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - NEXT_PUBLIC_API_URL=${NEXT_PUBLIC_API_URL:-http://localhost:4000}
    restart: unless-stopped
    networks:
      - nasalinha-network

networks:
  nasalinha-network:
    driver: bridge
