# Docker Compose para NaSalinha Backend (usando Supabase)
services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: nasalinha-backend
    ports:
      - "4000:4000"
    environment:
      - NODE_ENV=production
      - DATABASE_URL=${DATABASE_URL}
      - DIRECT_URL=${DIRECT_URL}
      - JWT_SECRET=${JWT_SECRET}
      - PORT=4000
      - CORS_ORIGIN=${CORS_ORIGIN:-http://localhost:3000}
    env_file:
      - .env
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "--spider", "-q", "http://localhost:4000/api"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
